export const SPELLS = {
    AIR_WALK: "Compendium.pf2e.spells-srd.Item.b5sGjGlBf58f8jn0",
    ACID_GRIP: "Compendium.pf2e.spells-srd.Item.9h9YCncqah6VNsKf",
    ACID_SPLASH: "Compendium.pf2e.spells-srd.Item.gISYsBFby1TiXfBt",
    ACIDIC_BURST: "Compendium.pf2e.spells-srd.Item.rnNGALRtsjspFTws",
    AUGURY: "Compendium.pf2e.spells-srd.Item.41TZEjhO6D1nWw2X",
    AQUEOUS_ORB: "Compendium.pf2e.spells-srd.Item.oUDNCArkQTdhllxD",
    BITING_WORDS: "Compendium.pf2e.spells-srd.Item.yafsV0ni7rFgqJBj",
    BLUR: "Compendium.pf2e.spells-srd.Item.3JG1t3T4mWn6vTke",
    BULLHORN: "Compendium.pf2e.spells-srd.Item.W02bHXylIpoXbO4e",
    BURNING_BLOSSOMS: "Compendium.pf2e.spells-srd.Item.kWDt0JcKPgX6MvdD",
    CANTICLE_OF_EVERLASTING_GRIEF: "Compendium.pf2e.spells-srd.Item.qlxM7Ik3uUeUIOcv",
    CAUSTIC_BLAST: "Compendium.pf2e.spells-srd.Item.thAHF1zxNplLCJPO",
    CHILLING_SPRAY: "Compendium.pf2e.spells-srd.Item.8TQiFzGf4feoHeH0",
    CLAIRVOYANCE: "Compendium.pf2e.spells-srd.Item.zvKWclOZ7A53DObE",
    CONFUSING_COLORS: "Compendium.pf2e.spells-srd.Item.uEyfLoFQsRKBRIcB",
    CREATION: "Compendium.pf2e.spells-srd.Item.TUj8eugNqAvB1vVR",
    CURSED_METAMORPHOSIS: "Compendium.pf2e.spells-srd.Item.dN8QBNuTiaBHCKUe",
    DAZE: "Compendium.pf2e.spells-srd.Item.4gBIw4IDrSfFHik4",
    DETECT_MAGIC: "Compendium.pf2e.spells-srd.Item.gpzpAAAJ1Lza2JVl",
    DINOSAUR_FORM: "Compendium.pf2e.spells-srd.Item.KhM8MhoUgoUjBMIz",
    DIVINE_DECREE: "Compendium.pf2e.spells-srd.Item.sX2o0HH4RjJDAZ8C",
    DIVINE_LANCE: "Compendium.pf2e.spells-srd.Item.qwZBXN6zBoB9BHXE",
    DIVINE_WRATH: "Compendium.pf2e.spells-srd.Item.hVU9msO9yGkxKZ3J",
    DRAW_THE_LIGHTNING: "Compendium.pf2e.spells-srd.Item.n7OgbKme4hNwxVwQ",
    ELECTRIC_ARC: "Compendium.pf2e.spells-srd.Item.kBhaPuzLUSwS6vVf",
    ENERVATION: "Compendium.pf2e.spells-srd.Item.eexkxcqnkXazsGfK",
    ENLARGE: "Compendium.pf2e.spells-srd.Item.wzctak6BxOW8xvFV",
    FEAR: "Compendium.pf2e.spells-srd.Item.4koZzrnMXhhosn0D",
    FEET_TO_FINS: "Compendium.pf2e.spells-srd.Item.RvBlSIJmxiqfCpR9",
    FIELD_OF_LIFE: "Compendium.pf2e.spells-srd.Item.x5rGOmhDRDVQPrnW",
    FIGMENT: "Compendium.pf2e.spells-srd.Item.0zU8CPejjQFnhZFI",
    FIREBALL: "Compendium.pf2e.spells-srd.Item.sxQZ6yqTn0czJxVd",
    FORBIDDING_WARD: "Compendium.pf2e.spells-srd.Item.RA7VKcen3p56rVyZ",
    FROSTBITE: "Compendium.pf2e.spells-srd.Item.IxhGEKl63R4QBvkj",
    GALE_BLAST: "Compendium.pf2e.spells-srd.Item.dDiOnjcsBFbAvP6t",
    GHOST_SOUND: "Compendium.pf2e.spells-srd.Item.atlgGNI1E1Ox3O3a",
    GOUGING_CLAW: "Compendium.pf2e.spells-srd.Item.MPxbKoR54gkYkqLO",
    GUIDANCE: "Compendium.pf2e.spells-srd.Item.izcxFQFwf3woCnFs",
    HARM: "Compendium.pf2e.spells-srd.Item.wdA52JJnsuQWeyqz",
    HAUNTING_HYMN: "Compendium.pf2e.spells-srd.Item.b5BQbwmuBhgPXTyi",
    HEAL: "Compendium.pf2e.spells-srd.Item.rfZpqmj0AIIdkVIs",
    HEALING_WELL: "Compendium.pf2e.spells-srd.Item.CzjQtkRuRlzRvwzg",
    HOWLING_BLIZZARD: "Compendium.pf2e.spells-srd.Item.xxWhyl81w3ckslAU",
    HYDRAULIC_TORRENT: "Compendium.pf2e.spells-srd.Item.Y3G6Y6EDgCY0s3fq",
    HYPNOTIZE: "Compendium.pf2e.spells-srd.Item.K2WpC3FFoHrqX9Q5",
    ICE_STORM: "Compendium.pf2e.spells-srd.Item.kHyjQbibRGPNCixx",
    IGNITION: "Compendium.pf2e.spells-srd.Item.6DfLZBl8wKIV03Iq",
    KNOW_THE_WAY: "Compendium.pf2e.spells-srd.Item.tXa5vOu5giBNCjdR",
    LIGHT: "Compendium.pf2e.spells-srd.Item.WBmvzNDfpwka3qT4",
    LIGHTNING_BOLT: "Compendium.pf2e.spells-srd.Item.9AAkVUCwF6WVNNY2",
    MAGNETIC_ACCELERATION: "Compendium.pf2e.spells-srd.Item.Tx8OqkBFA2QlaldW",
    MESSAGE: "Compendium.pf2e.spells-srd.Item.vLzFcIaSXs7YTIqJ",
    MIRRORS_MISFORTUNE: "Compendium.pf2e.spells-srd.Item.A7w3YQBrFNH8KYsB",
    MIRROR_MALEFACTORS: "Compendium.pf2e.spells-srd.Item.CmZCq4htcZ6W0TKk",
    NEEDLE_DARTS: "Compendium.pf2e.spells-srd.Item.iYRDFxeVpJ5KIjmr",
    NOISE_BLAST: "Compendium.pf2e.spells-srd.Item.wzLkNU3AAqOSKFPR",
    NOXIOUS_VAPOURS: "Compendium.pf2e.spells-srd.Item.1meVElIu1CEVYWkv",
    ONE_WITH_STONE: "Compendium.pf2e.spells-srd.Item.vh1RpbWfqdNC4L3P",
    OUTCASTS_CURSE: "Compendium.pf2e.spells-srd.Item.KSAEhNfZyXMO7Z7V",
    PAINFUL_VIBRATIONS: "Compendium.pf2e.spells-srd.Item.qTzvVnAMWL05VitC",
    PETAL_STORM: "Compendium.pf2e.spells-srd.Item.D31YX7zvRBvenTAz",
    PHANTASMAL_CALAMITY: "Compendium.pf2e.spells-srd.Item.0XP2XOxT9VSiXFDr",
    PHANTASMAL_TREASURE: "Compendium.pf2e.spells-srd.Item.L0GoJpHxSD0wRY5k",
    PLANT_FORM: "Compendium.pf2e.spells-srd.Item.zCcfPS4y5SrZzU2x",
    PRESTIDIGITATION: "Compendium.pf2e.spells-srd.Item.Qw3fnUlaUbnn7ipC",
    PUFF_OF_POISON: "Compendium.pf2e.spells-srd.Item.D7ZEhTNIDWDLC2J4",
    RAY_OF_FROST: "Compendium.pf2e.spells-srd.Item.gYjPm7YwGtEa1oxh",
    READ_AURA: "Compendium.pf2e.spells-srd.Item.OhD2Z6rIGGD5ocZA",
    RESTORATION: "Compendium.pf2e.spells-srd.Item.SnaLVgxZ9ryUFmUr",
    RUST_CLOUD: "Compendium.pf2e.spells-srd.Item.yy2K51kK3a60rRIe",
    SCATTER_SCREE: "Compendium.pf2e.spells-srd.Item.zA0jNIBRgLsyTpbm",
    SCOUTING_EYE: "Compendium.pf2e.spells-srd.Item.Ek5XI0aEdZhBgm21",
    SHIELD: "Compendium.pf2e.spells-srd.Item.TVKNbcgTee19PXZR",
    SIGIL: "Compendium.pf2e.spells-srd.Item.AUctDF2fqPZN2w4W",
    SOOTHING_BLOSSOMS: "Compendium.pf2e.spells-srd.Item.5XUn9NADr05IyiVw",
    SOUND_BODY: "Compendium.pf2e.spells-srd.Item.Et8RSCLx8w7uOLvo",
    SPIKE_STONES: "Compendium.pf2e.spells-srd.Item.3xD8DYrr8YDVYGg7",
    SPRITUAL_ARMAMENT: "Compendium.pf2e.spells-srd.Item.WPu3UE3kTXSLqO40",
    SPRITUAL_GUARDIAN: "Compendium.pf2e.spells-srd.Item.jQdm301h6e8hIY4U",
    SPIRITUAL_WEAPON: "Compendium.pf2e.spells-srd.Item.Fq9yCbqI2RDt6Orw",
    SPOUT: "Compendium.pf2e.spells-srd.Item.eSL5hVT9gXrnRLtd",
    STABILIZE: "Compendium.pf2e.spells-srd.Item.SnjhtQYexDtNDdEg",
    SUMMON_ANIMAL: "Compendium.pf2e.spells-srd.Item.4YnON9JHYqtLzccu",
    SUMMON_DEIFIC_HERALD: "Compendium.pf2e.spells-srd.Item.kIRWUBxocERjIBni",
    TAME: "Compendium.pf2e.spells-srd.Item.s7ILzY2xh1tc9U1v",
    TANGLE_VINE: "Compendium.pf2e.spells-srd.Item.uZK2BYzPnxUBnDjr",
    TELEKINETIC_HAND: "Compendium.pf2e.spells-srd.Item.pwzdSlJgYqN7bs2w",
    TELEKINETIC_PROJECTILE: "Compendium.pf2e.spells-srd.Item.60sgbuMWN0268dB7",
    TIMBER: "Compendium.pf2e.spells-srd.Item.9I8mp7RkjeXbkYfx",
    WALL_OF_FIRE: "Compendium.pf2e.spells-srd.Item.IarZrgCeaiUqOuRu",
    WALL_OF_THORNS: "Compendium.pf2e.spells-srd.Item.KsWhliKfUs3IpW3c",
    WALL_OF_WIND: "Compendium.pf2e.spells-srd.Item.it4ZsAi6XgvGcodc",
    WAVE_OF_DESPAIR: "Compendium.pf2e.spells-srd.Item.GaRQlC9Yw1BGKHfN",
    WEB_OF_EYES: "Compendium.pf2e.spells-srd.Item.XQSPJHOf3TyfqvgS",
    VAMPIRIC_EXSANGUINATION: "Compendium.pf2e.spells-srd.Item.fd31tAHSSGXyOxW6",
    VAMPIRIC_FEAST: "Compendium.pf2e.spells-srd.Item.N1Z1oLPdBxaSgrEE",
    VIBRANT_PATTERN: "Compendium.pf2e.spells-srd.Item.RQjSQVZRG497cJhX",
    VISION_OF_DEATH: "Compendium.pf2e.spells-srd.Item.Jmxru8zMdYMRuO5n",
    VITAL_BEACON: "Compendium.pf2e.spells-srd.Item.ikSb3LRGnrwXJBVX",
    VITALITY_LASH: "Compendium.pf2e.spells-srd.Item.kcelf6IHl3L9VXXg",
    VOID_WARP: "Compendium.pf2e.spells-srd.Item.mAMEt4FFbdqoRnkN",
};

export const SPELLHEART_EFFECTS = {
    "brightbloom-posy": {
        weapon: "",
    },
    "clay-sphere": {
        weapon: "Compendium.pf2e.equipment-effects.Item.La2ziyuLYKG0thOj",
    },
    "desolation-locket": {
        weapon: "Compendium.pf2e.equipment-effects.Item.NwEVRZmLbM9QKoIH",
    },
    "enigma-mirror": {
        armor: "Compendium.pf2e-item-activations.item-activations-effects.Item.DWZgLolqLRcfQb5W",
        weapon: "Compendium.pf2e-item-activations.item-activations-effects.Item.ydHmaMoiG1HupZm9",
    },
    "five-feather-wreath": {
        weapon: "Compendium.pf2e.equipment-effects.Item.nQ6vM1CRLyvQdGLG",
    },
    "flaming-star": {
        weapon: "Compendium.pf2e.equipment-effects.Item.OxCVZSvWVJsOGAZN",
    },
    "fox-glove-token": {
        weapon: "",
    },
    "grim-sandglass": {
        weapon: "Compendium.pf2e.equipment-effects.Item.V4JoVnOfKze8cRan",
    },
    heartmoss: {
        weapon: "",
    },
    "jolt-coil": {
        weapon: "Compendium.pf2e.equipment-effects.Item.mHIdEC7RX6isILiM",
    },
    "judgment-thurible": {
        armor: "",
        weapon: "",
    },
    "lightweave-scarf": {
        weapon: "",
    },
    "perfect-droplet": {
        armor: "Compendium.pf2e.equipment-effects.Item.VZCcjwsQX1wnYlTn",
    },
    "pickled-demon-tongue": {
        weapon: "Compendium.pf2e.equipment-effects.Item.LbaYzs0dQuFj8FXJ",
    },
    "polished-demon-horn": {
        weapon: "Compendium.pf2e.equipment-effects.Item.WARLTi8unmPgmnNw",
    },
    "rime-crystal": {
        weapon: "Compendium.pf2e.equipment-effects.Item.IiDpW99zrh7zHxmQ",
    },
    "sanguine-fang": {
        weapon: "Compendium.pf2e.equipment-effects.Item.bKEx53h6lrFOYvpu",
    },
    "spiny-lodestone": {
        weapon: "Compendium.pf2e.equipment-effects.Item.m6z7OrJgF4XQFNpa",
    },
    "thorn-triad": {
        armor: "Compendium.pf2e.equipment-effects.Item.JaPNzmgD7p7hHH8o",
        weapon: "Compendium.pf2e.equipment-effects.Item.FTj94xTqZbaCs4jT",
    },
    "trinity-geode": {
        armor: "Compendium.pf2e.equipment-effects.Item.oqwrw6XztVlS9tEG",
        weapon: "Compendium.pf2e.equipment-effects.Item.WRV0XjiEHdlBpduS",
    },
    "warding-statuette": {
        weapon: "Compendium.pf2e.equipment-effects.Item.gwiyabYi92R97bXZ",
    },
};
